### ISSUE TITLE
GitHub update broke plugin?

### ISSUE THREAD

**Issue by frdmn** [sindresorhus/github-notifier-chrome#26] opened 2015-07-20 07:15 UTC
The plugin doesn't seem to work for me. 

Perhaps this has something to do with the latest navbar update in the GitHub frontend?

**Comment by PeterDaveHello** [comment] 2015-07-20 07:45
I don't have this problem.

Ver 2.0 on Chromium Version 43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)

**Comment by attilaolah** [comment] 2015-07-20 09:35
Version 2.0 doesn't depend on the navbar. What version are you using, @frdmn? Have you [set up a token][1]?

[1]: chrome-extension://lmjdlojahmbbcodnpecnjnmlddbkjhnn/options.html

**Comment by arthurvr** [comment] 2015-07-24 18:26
I cannot reproduce this eighter, on latest stable and on canary.

> What version are you using, @frdmn? Have you set up a token?

Closing for now. Happy to reopen when you give us the information we need ;)

**Closed by arthurvr** 2015-07-24 18:26 UTC
